title: Takuro Fujino / MeF[0504]
description: { { page.description } }
theme: jekyll-theme-cayman
# https://pages.github.com/themes/
exclude:
  - README.md
  - LICENSE.txt
  - .gitignore
show_downloads: true
lang: ja
